### ISSUE TITLE
Permission denied due to missing filter for find_dfu_devices

### ISSUE THREAD

**Issue by lancelot666de** [greatscottgadgets/pyfwup#4]
When having USB devices exposing a DFU interface, greatfet firmware fails with a permission denied. 

The reason seems that the arguments filtering the device are not passed to the function _find_dfu_devices_. Changing the call from 
```
list(self.find_dfu_devices())  
```

to 

```
list(self.find_dfu_devices(*args, **kwargs))
```
seems to fix the problem. The diff between the working version and the version of the repo is given next:

```
140c140
<         devices = list(self.find_dfu_devices(*args, **kwargs))
---
>         devices = list(self.find_dfu_devices())
```

**Comment by antoinevg** [comment]
Fixed in #5
